### ISSUE TITLE
How to change font?

### ISSUE THREAD

**Issue by MasterGroosha** [Psycojoker/prosopopee#105]
Pardon my ignorance, I'm not a web dev at all. 
The problem is that default crimson font doesn't look good with text in Russian. I've created a `custom.css` file with 
```css
body {
    font-family: 'Roboto', sans-serif !important;
}
```
block, but the font itself isn't changed. I'm sure that file placement is correct since adding a `custom.js` affects the website. How can I change font to something else?
