### ISSUE TITLE
full-picture with space in filename does not render

### ISSUE THREAD

**Issue by gangelop** [Psycojoker/prosopopee#115]
full-picture with space in filename does not render
In a gallery `settings.yaml`, the image with filename `test pic.jpg` does not render in the browser. There's just a gray background.
```yaml
sections:
    - type: full-picture
      image: test pic.jpg
```
It works if the space is removed (and the underlying file appropriately renamed).
```yaml
sections:
    - type: full-picture
      image: test-pic.jpg
```
I'm a bit at a loss with this one. No idea what's causing it.
