### ISSUE TITLE
video conversions fail with space in filename

### ISSUE THREAD

**Issue by gangelop** [Psycojoker/prosopopee#116]
this
```yaml
sections:
    images:
      -
         - type: video
           name: "cool video.mp4"
```
causes this
```
Generation: ./gallery1/cool video.mp4
ffmpeg -loglevel error -i ./gallery1/cool video.mp4 -c:v libvpx -b:v 3900k -qmin 10 -qmax 42 -maxrate 500k -bufsize 1500k -c:a libvorbis -b:v 100k -s 1280x720 -f webm -y "./build/gallery1/cool video.mp4.webm"
./gallery1/cool: No such file or directory
Abort: ffmpeg command failed
```
Some quotes are needed for `{source}` and `{target}` in `prosopopee/prosopopee.py`.
